### ISSUE TITLE
[AVM Module Issue]: Add ability to specify custom `port` in `backend_http_settings`

### ISSUE THREAD

**Issue by vitalii-dubovoi** [Azure/terraform-azurerm-avm-res-network-applicationgateway#55]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.1

### Description

I am using your module to configure `backend_http_settings` for Azure Application Gateway, but I have encountered a restriction where the port can only be set to `80` or `443`, based on the value of enable_https.

This is limiting because, in the Azure Portal UI for Application Gateway, it is possible to specify any custom port. However, the module seems to enforce this restriction, which prevents me from setting up non-standard ports like `8080` for my backend services.

Is this restriction intentional, and if so, is there a way to configure the module to support custom ports as allowed in the UI?
![image](https://github.com/user-attachments/assets/6f3fb014-e4c3-4b3d-9e7b-dc3087d38649)
![image](https://github.com/user-attachments/assets/a2e8c41e-42d6-4a18-baf8-37f1733cc4c2)

**Comment by matt-FFFFFF** [comment]
@mofaizal can you comment here?

**Comment by mofaizal** [comment]
Thanks for the feedback, will try add custom port :-)
