### ISSUE TITLE
[AVM Question/Feedback]: Variable condition limit too short

### ISSUE THREAD

**Issue by RelaxingLoki475** [Azure/terraform-azurerm-avm-res-network-applicationgateway#58]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi, variables condition limits to 24 characters for name and public_ip_name are too short. Isn't it?

**Comment by mofaizal** [comment]
Thanks for highlighting it next PR this will be update to 1-80 Alphanumerics, underscores, periods, and hyphens.
