### ISSUE TITLE
[AVM Module Issue]: probe_configuration

### ISSUE THREAD

**Issue by RelaxingLoki475** [Azure/terraform-azurerm-avm-res-network-applicationgateway#59]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.1

### Description

In probe_configurations, match definition is not applied. Therefore probe changes are proposed in every apply.

**Comment by mofaizal** [comment]
Can you please provide me example or the scenario for me test or understand the ask better.

**Comment by RelaxingLoki475** [comment]
Sure, application gateway by default add a match condition to custom probe even if not provided.
In that case on each apply probe change are proposed.
Even if match status?code is provided, that configuration is not passed to 
in probe_configuration with match.status_code defined:
  probe_configurations = {
    app_service = {
      name                = azurerm_windows_web_app.public_web_service.name
      host                = azurerm_windows_web_app.public_web_service.default_hostname
      protocol            = "Https"
      path                = "/"
      interval            = 30
      timeout             = 60
      unhealthy_threshold = 5
      # pick_host_name_from_backend_http_settings = true
      **match = {
        status_code = ["200-399"]
      }**
    }
  }

that definition is not passed to probe configuration
![Image](https://github.com/user-attachments/assets/1429dd1a-1a54-44e8-a4b6-260e1ad37c66)
