### ISSUE TITLE
[AVM Module Issue]: AVM specification alignment, public IP resource should not be present in the main module?

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#67]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

The AVM specification states that resources should only contain resources that are relevant to the resource provider scope and their sub resources

With this in mind, I believe the public IP address resource should be removed.

It is also adviseable to avoid unnecessary data objects.  I would recommend removing the subnet data block and instead supplying a subnet ID, which co-incidentally allows for subnets in different resource groups as well.

**Comment by mofaizal** [comment]
It aligns with the application gateway dependency requirement. We discussed it internally and decided to maintain the same setup as the portal experience. Thanks for the suggestion. We will create a public IP along with the application gateway.

**Comment by kewalaka** [comment]
Thanks for the update. If you can create a branch i will update the PR to re-add the pip.  I'll add a comment in the code to note this decision.  I would like to keep credit for the changes so would appreciate if I can PR against this branch please.

Thanks for the prompt feedback on the issues 😀

**Comment by mofaizal** [comment]
Certainly, I will create the branch and update you on its status. I completely agree with you regarding the credit. In an open source community, recognition should be given in line with the effort contributed.
