### ISSUE TITLE
[AVM Module Issue]: identity_ids should be managed_identities

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#68]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

the share AVM specification requires managed identities to be specified as per this:

https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#managed-identities

**Comment by mofaizal** [comment]
@kewalaka Thank you. Integrating Manage Identity and private endpoint is part of the roadmap. I appreciate your suggestion and updating the code; I will create a separate branch for testing before merging it into the PR.
