### ISSUE TITLE
[AVM Module Issue]: many variable blocks are missing heredoc descriptions

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#69]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

descriptions should use the heredoc format and include per parameter guidance, ref spec:

https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr1---category-documentation---descriptions

**Comment by kewalaka** [comment]
i've got these descriptions in another project so I'll raise a PR to remediate.

**Comment by mofaizal** [comment]
@kewalaka Thanks, I appreciate your suggestion and updating the code; I will create a separate branch for testing before merging it into the PR.
