### ISSUE TITLE
[AVM Module Issue]: consumers of the module should be able to override naming conventions for FEIP/GWIP

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#70]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

The front end IP configuration name & gateway IP configuration name is inferred from the ``name`` variable and the format cannot be overridden by a module consumer - spec reference:

https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr25---category-composition---resource-naming

**Comment by mofaizal** [comment]
@kewalaka Thanks, I appreciate your suggestion and updating the code; I will create a separate branch for testing before merging it into the PR.
