### ISSUE TITLE
[AVM Module Issue]: keyvault self ssl example recommendations

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#71]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

If using an external WAF configuration (as is advised), it is not necessary to include a waf_configuration block here:

https://github.com/kewalaka/terraform-azurerm-avm-res-network-applicationgateway-upstream/blob/f890af9e28f013b937ae038881d5e7cfe8b66bfd/examples/kv_selfssl_waf_https_app_gateway/main.tf#L147-L154

The Keyvault should not be using access policies, instead Azure RBAC should be used, and the permissions applied are not following least privilege.

**Comment by kewalaka** [comment]
there are also several unnecessary depends on blocks - if directly referencing an attribute from another resource it is not necessary to do this;

e.g.

```terraform
# Required for to deploy VMSS and Web Server to host application
resource "azurerm_subnet" "workload" {
  address_prefixes     = ["10.90.2.0/24"]
  name                 = "workload"
  resource_group_name  = azurerm_resource_group.rg_group.name
  virtual_network_name = azurerm_virtual_network.vnet.name

  depends_on = [azurerm_virtual_network.vnet, azurerm_resource_group.rg_group]
}
```

The above ``depends_on`` is not needed because the resources are directly referenced.

**Comment by kewalaka** [comment]
rather than create a self signed certificate via bash, it is also possible to do this in a more terraform-like way via the tls provider.  

https://registry.terraform.io/providers/hashicorp/tls/latest/docs

**Comment by mofaizal** [comment]
I agree, there is more than one method to achieve the same outcome. :-)
