### ISSUE TITLE
[AVM Module Issue]: the ``enable_https`` variable misses some scenarios (e.g. tcp)

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#72]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

The backend pool summarises the port & protocol choices into a single variable ``enable_https``.  This is a nice helper, but it excludes certain choices, such as tcp for backend services that do not use http.

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-components#protocols

I recommend retaining the original parameters, port & protocol.

**Comment by mofaizal** [comment]
I appreciate your suggestion and updating the code; I will create a separate branch for testing before merging it into the PR.
