### ISSUE TITLE
[AVM Module Issue]: make ssl_policy secure by default

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#82]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.0

### Description

the ssl_policy is null by default which deploys AppGwSslPolicy20150501, which supports legacy TLS protocols 

to align with the content on learn the secure by default option should be AppGwSslPolicy20220101

ref: https://learn.microsoft.com/en-nz/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy

```terraform
  # for ssl_policy
  default = {
    policy_name = "AppGwSslPolicy20220101"
    policy_type = "Predefined"
  }
```

we should also check that if an ssl_policy is overridden via an ssl_profile that this is also secure by default (I think if nothing is specified it inherits from the default listener.

**Comment by mofaizal** [comment]
Thanks for the feedback, when you provide input value as the code assign "AppGwSslPolicy20220101" please refer screenshot. 

  ssl_policy = {
    policy_name = "AppGwSslPolicy20220101"
    policy_type = "Predefined"
  }

![Image](https://github.com/user-attachments/assets/d9009a92-d682-4cd0-be49-e2cfc62f2067)

**Comment by mofaizal** [comment]
The changes updated on version 0.3.0 branch, the example stated on https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/tree/version-0.3.0/examples/kv_selfssl_waf_https_app_gateway please take look
