### ISSUE TITLE
[AVM Module Issue]: Wrong Constraints for hashicorp/random

### ISSUE THREAD

**Issue by thamjayshen** [Azure/terraform-azurerm-avm-res-network-applicationgateway#84]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### (Optional) Module Version

0.2.0

### Description

Error:
Could not retrieve the list of available versions for provider hashicorp/random: no available releases match the given constraints >= 3.5.0, ~> 3.5.0, ~> 3.5, >= 3.5.1, ~> 3.6, >= 3.6.2, < 4.0.0

Discussion:
In terraform.tf the hashicorp/random was changed from version = ">3.5.0" to version = "~>3.5.0".  However this limits to only versions 3.5.X and will have impact on other modules that require higher versions. 

Fix:
Instead it should be version = "~>3.5"

**Comment by But4ler** [comment]
You beat me by 7 hours to open the same issue ^^

**Comment by mofaizal** [comment]
Thanks for the feedback, given below the details.

= 3.5.0: Allows 3.5.0 and any newer version.
~> 3.5.0: Allows only patch updates in the 3.5 series (e.g., 3.5.x).
= 3.5, < 5: Allows any version between 3.5 and up to but not including 5.
=> 3.5: Not valid syntax; likely intended to mean >= 3.5.

I will change to tf provider to following to meet the need. :-)

terraform {
required_version = ">= 1.5"
required_providers {
azurerm = {
source = "hashicorp/azurerm"
version = ">= 3.71"
}
modtm = {
source = "Azure/modtm"
version = ">= 0.3"
}
random = {
source = "hashicorp/random"
version = ">= 3.5.0"
}
}
}

**Comment by mofaizal** [comment]
The changes right now at branch version 0.3.0, possible please validate let me know your feedback, if not comment or changes i will merge with main and release it.
