### ISSUE TITLE
[AVM Module Issue]: Support Azurerm 3 and 4

### ISSUE THREAD

**Issue by But4ler** [Azure/terraform-azurerm-avm-res-network-applicationgateway#87]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.2.0

### Description

Hello,

Would it be possible to support both azurerm 3.x and 4.x, please? For example, here: https://github.com/Azure/terraform-azurerm-avm-res-network-firewallpolicy/blob/main/terraform.tf#L5

Some of the AVM modules handle both versions, some only handle version 3, and others only version 4, which creates incompatibilities and forces us to fork (AVM VPN Gateway v4, Vnet in v3, etc.).

Thank you.
Exemple:
```hcl
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71, < 5.0.0"
    }
```

**Comment by mofaizal** [comment]
Thanks for the feedback, given below the details.

= 3.5.0: Allows 3.5.0 and any newer version.
~> 3.5.0: Allows only patch updates in the 3.5 series (e.g., 3.5.x).
= 3.5, < 5: Allows any version between 3.5 and up to but not including 5.
=> 3.5: Not valid syntax; likely intended to mean >= 3.5.

I will change to tf provider to following to meet the need. :-)

terraform {
required_version = ">= 1.5"
required_providers {
azurerm = {
source = "hashicorp/azurerm"
version = ">= 3.71"
}
modtm = {
source = "Azure/modtm"
version = ">= 0.3"
}
random = {
source = "hashicorp/random"
version = ">= 3.5.0"
}
}
}

**Comment by mofaizal** [comment]
The changes right now at branch version 0.3.0, possible please validate let me know your feedback, if not comment or changes i will merge with main and release it.
