### ISSUE TITLE
[AVM Question/Feedback]:

### ISSUE THREAD

**Issue by RelaxingLoki475** [Azure/terraform-azurerm-avm-res-network-applicationgateway#89]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Hello,
why do you change version for provider random from >=3.5.0 to ~>3.5.0

**Comment by But4ler** [comment]
Hello, terraform AVM modules have a version fragmentation problem that makes them incompatible with each other.

https://github.com/Azure/Azure-Verified-Modules/issues/1576

~>3.5.0  lock auto upgrade to 3.5.x only
~>3.5  lock auto upgrade to 3.x only
>= 3.5  allow auto upgrade to the new major version

**Comment by mofaizal** [comment]
Thanks for the feedback, given below the details. 

>= 3.5.0: Allows 3.5.0 and any newer version.
~> 3.5.0: Allows only patch updates in the 3.5 series (e.g., 3.5.x).
>= 3.5, < 5: Allows any version between 3.5 and up to but not including 5.
=> 3.5: Not valid syntax; likely intended to mean >= 3.5.


I will change to tf provider to following to meet the need. :-) 

terraform {
  required_version = ">= 1.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.71"
    }
    modtm = {
      source  = "Azure/modtm"
      version = ">= 0.3"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.5.0"
    }
  }
}

**Comment by mofaizal** [comment]
The changes right now at branch version 0.3.0, possible please validate let me know your feedback, if not comment or changes i will merge with main and release it.
