### ISSUE TITLE
[AVM Module Request]: Application Gateway v2 Private Only ( with EnableApplicationGatewayNetworkIsolation Preview feature)

### ISSUE THREAD

**Issue by But4ler** [Azure/terraform-azurerm-avm-res-network-applicationgateway#90]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

It is possible to support the Preview EnableApplicationGatewayNetworkIsolation? feature.

EnableApplicationGatewayNetworkIsolation  ?

**Feature Description:** 
Enables ability to deploy Application Gateway v2 sku with private IP frontend configuration only, as well as enhance control over NSG and Route Table rules.
https://learn.microsoft.com/fr-fr/azure/application-gateway/application-gateway-private-deployment?WT.mc_id=Portal-Microsoft_Azure_Resources&tabs=portal

The current blockage comes from the Public IP, which is mandatory. 

I was able to test with the basic azurerm_application_gateway resource. 
The functionality is supported and the AGW v2 is private only.

```bash
export SUBSCRIPTION=<sub name>
az feature show --namespace "Microsoft.Network" --name "EnableApplicationGatewayNetworkIsolation" --subscription $SUBSCRIPTION
az feature register --namespace Microsoft.Network --name "EnableApplicationGatewayNetworkIsolation" --subscription $SUBSCRIPTION
az provider register -n Microsoft.Network --subscription $SUBSCRIPTION

# Verification
$ az feature show --namespace "Microsoft.Network" --name "EnableApplicationGatewayNetworkIsolation" --subscription $SUBSCRIPTION
{
  "id": "/subscriptions/****************providers/Microsoft.Features/providers/Microsoft.Network/features/EnableApplicationGatewayNetworkIsolation",
  "name": "Microsoft.Network/EnableApplicationGatewayNetworkIsolation",
  "properties": {
    "state": "Registering"
  },
  "type": "Microsoft.Features/providers/features"
}

**Comment by mofaizal** [comment]
Thanks for the feedback @But4ler it is already called out home page readme file.  Terraform provider not available due to preview, once provide supports we will update the module. 

Supported frontend IP configuration
For current general availability support, Application Gateway V2 supports the following combinations

- Private IP and Public IP
- Public IP only

**Comment by But4ler** [comment]
Hello
Ok, I understand, thanks for the feedback.
For your information, on other terraform AVM modules, preview functionalities can be activated 

https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/blob/main/main.virtual.network.tf#L39

It's not possible to use the same approach as in the other module? deactivated by default, but can be activated.
The only constraint, in terraform terms, is that the Public IP is not mandatory.

**Comment by kewalaka** [comment]
this is what the spec says on this:

https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr1---category-composition---preview-services

**Comment by But4ler** [comment]
ok, thanks anyway
