### ISSUE TITLE
[AVM Module Issue]: probe_configurations variable, host attribute should be optional

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-applicationgateway#91]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.0

### Description

reference:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#host

A probe block supports the following:

[host](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#host) - (Optional) The Hostname used for this Probe. If the Application Gateway is configured for a single site, by default the Host name should be specified as 127.0.0.1, unless otherwise configured in custom probe. Cannot be set if pick_host_name_from_backend_http_settings is set to true.

**Comment by mofaizal** [comment]
The changes right now at branch version 0.3.0, possible please validate let me know your feedback, if not comment or changes i will merge with main and release it.  

The example you can see at https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/tree/version-0.3.0/examples/simple_http_probe_app_gateway
