### ISSUE TITLE
[AVM Module Issue]: Unable to set user created frontend_ip_configuration_name for http_listeners

### ISSUE THREAD

**Issue by MinHeinA** [Azure/terraform-azurerm-avm-res-network-applicationgateway#93]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.0

### Description

Unable to set user created frontend_ip_configuration_name for http_listeners

```    
    frontend_ip_configuration_private = {
      name                          = "feip-prv-appgw-test-min-01"
      private_ip_address_allocation = "Static"
      private_ip_address            = "10.0.0.16"
    }
    http_listeners = {
      lsnr1 = {
        name                           = "pub-lsnr-appgw-test-min-01"
        frontend_ip_configuration_name = "feip-pup-appgw-test-min-01"
        frontend_port_name             = "port_80"
        host_name                      = "mintest2.com"
      }
    }
```

In plan http listener's frontend ip configuration will default to `pub-lsnr-appgw-test-min-01`
![Image](https://github.com/user-attachments/assets/c55f8bde-c9d3-4a49-b894-ca3d0cf87a0d)

It seems that in `http_listeners` variable in variables.tf of the module, child variable `frontend_ip_configuration_name` is missing, so the frontend configuration of http listeners will always defaults to `pub-lsnr-appgw-test-min-01` which is defined in locals.tf `${var.name}-feip` 
```
variable "http_listeners" {
  type = map(object({
    name               = string
    frontend_port_name = string
    # TODO add frontend_ip_configuration_name here
    firewall_policy_id   = optional(string)
    require_sni          = optional(bool)
    host_name            = optional(string)
    host_names           = optional(list(string))
    ssl_certificate_name = optional(string)
    ssl_profile_name     = optional(string)
    custom_error_configuration = optional(list(object({
      status_code           = string
      custom_error_page_url = string
    })))
    # Define other attributes as needed
  }))
  description = <<-DESCRIPTION 
```

**Comment by mofaizal** [comment]
The changes right now at branch version 0.3.0, possible please validate let me know your feedback, if not comment or changes i will merge with main and release it.  

The example you can see at https://github.com/Azure/terraform-azurerm-avm-res-network-applicationgateway/tree/version-0.3.0/examples/front_end_ip_private_custom_name
