### ISSUE TITLE
[AVM Module Issue]: Documentation bug in README and variables.tf

### ISSUE THREAD

**Issue by MinHeinA** [Azure/terraform-azurerm-avm-res-network-applicationgateway#96]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.2.0

### Description
There are documentation errors in the following files below:

README.md
Line no 193: Remove protocol as it is not required and its logic is decided in main.tf
line no 319: name instead of private_name

variables.tf
line no 117: Remove protocol as it is not required and its logic is decided in main.tf
line no 309: name instead of private_name

**Comment by mofaizal** [comment]
Thanks let me take look.
